### ISSUE TITLE
[Bug][0.1.17]if "optimizedInventories" true, hoppers can't put items in composters

### ISSUE THREAD

**Issue by Harveykang** [2No2Name/hopperOptimizations#10]
![image](https://user-images.githubusercontent.com/46108547/77387806-4d3e3d00-6dc9-11ea-8d3c-c23b4d3d07b7.png)
![image](https://user-images.githubusercontent.com/46108547/77387809-50392d80-6dc9-11ea-9174-9cc7c806d668.png)
can only put in 1 or 2 item, then it's stuck

**Comment by 2No2Name** [comment]
Thank you for the bug report. I changed some stuff regarding the composter interactions in that update.

**Comment by 2No2Name** [comment]
Fixed in 0.1.18
