### ISSUE TITLE
[Bug][0.1.17]"optimizedInventories"true, the server screen spams "[STDOUT]: Hopper is full even though it wasn't"

### ISSUE THREAD

**Issue by Harveykang** [2No2Name/hopperOptimizations#11]
![image](https://user-images.githubusercontent.com/46108547/77964261-5bccad00-7311-11ea-8548-42f027256575.png)
server reports like this only when minecart is full
![image](https://user-images.githubusercontent.com/46108547/77964378-8a4a8800-7311-11ea-947e-58d077fd5ccd.png)

**Comment by 2No2Name** [comment]
That means that for some reason hopper minecarts try to pull items even when they are full, I will look into that and whether disabling that changes behavior in regards of useless comparator updates

**Comment by 2No2Name** [comment]
Fixed in 0.1.18
