### ISSUE TITLE
Installation details

### ISSUE THREAD

**Issue by Luckey-Elijah** [2No2Name/hopperOptimizations#15]
Hello!

I'm new to mods in general, but really like the concept of this mod.

In the readme could you provide instructions to installing the mod? Even if it's high-level, that's totally fine, I just need a bit of direction.

Best,
Elijah.

**Comment by DragonEggBedrockBreaking** [comment]
Look at this video on how to download the carpet mod: https://www.youtube.com/watch?v=F7HAzxVN2Is&t=190s
Also download https://github.com/2No2Name/lithium-fabric/releases and https://github.com/2No2Name/hopperOptimizations/releases and at 03:08 in the video do the same for the extra mods you need to download.

**Comment by DragonEggBedrockBreaking** [comment]
If this helped please close the issue.

**Comment by Luckey-Elijah** [comment]
Helps!

Thank you.
