### ISSUE TITLE
Server unresponsive when item unloader starts running

### ISSUE THREAD

**Issue by josephrooks** [2No2Name/hopperOptimizations#17]
I finally got around to installing your build of Lithium + the 1.16.1 w/ Lithium build of HopperOptimizations.

When I drop a Shulker into my item unloader ([this design](https://www.youtube.com/watch?v=xy5K6pQRAlQ)), the server becomes unresponsive. 100% CPU usage, nothing in the console, players time out and I have to kill the process. This only happens with Shulkers, not with loose items.

Based on the Redstone lighting up, it seems like it's happening one of two places:
- at the point when the dropper would try to spit the Shulker into another Shulker to split shulkers and normal items, or
- when it's trying to dispense the Shulker in place to start unloading it

I think it's the former because I don't hear the piston trigger to break the previous shulker, but I'm not 100% sure since everything client side freezes up pretty quickly.

Just to be thorough, I tested it without HopperOpts, but with both versions of Lithium (yours and Jelly's) and it goes back to working fine.

Anything in particular I should do to try to get more useful info since there's nothing in the log after I have to kill it?

**Comment by 2No2Name** [comment]
I fixed this in the latest version.
