### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by ghost** [2No2Name/hopperOptimizations#19]
Appears to break hopper minecart hopper interaction in specific scenarios, server only. 
Running exclusively hopper optimization along with your fork of lithium hopper minecarts either reloaded while on hopper or being unloaded while on hopper causes a bug in which simple redstone circuits break. As seen here https://youtu.be/82N8c3tCgFk

[hopper break2.zip](https://github.com/2No2Name/hopperOptimizations/files/5301653/hopper.break2.zip)

To recreate has to be on server.
1) launch server upon joining /tp -133.55 27.00 15.30 you will observe normal hopper minecart unloading behaviors
2) log out and back into server while the minecart is on the hopper being unloaded.
3) upon relogging upon next pass of hopper minecart it will not be fully unloaded only taking 1-3 items out before rail being powered.

**Comment by 2No2Name** [comment]
The video is private, can you switch it to unlisted or public?

**Comment by ghost** [comment]
Apologies video is now unlisted.

**Comment by 2No2Name** [comment]
Something big is going wrong when unloading chunks. Thanks for reporting. I will look into it

**Comment by 2No2Name** [comment]
Fixed in https://github.com/2No2Name/hopperOptimizations/releases/tag/v0.3.4

**Comment by ghost** [comment]
Awesome can confirm issue has been fixed in new release. Thank you for extremely quick fix.
