### ISSUE TITLE
Hoppers do not suck items out of dropper in some instances

### ISSUE THREAD

**Issue by FrostieBits** [2No2Name/hopperOptimizations#2]
When optimizedInventories is enabled there appears to be a condition where a hopper will push items into a dropper, but a hopper will not suck items out of it, unless you 'observe' the dropper, i.e. open the GUI.

I have attached schematic to reproduce the issue (I'm sure a slightly simpler test case could be created)

[Optimise Inventory Test.zip](https://github.com/2No2Name/hopperOptimizations/files/3858224/Optimise.Inventory.Test.zip)

**Comment by 2No2Name** [comment]
Thank you for the issue report. I fixed this in 0.1.4, it was caused by using an old instance of the dropper's inventory.
