### ISSUE TITLE
hopper fails to send item into dropper rehappened

### ISSUE THREAD

**Issue by aria1th** [2No2Name/hopperOptimizations#20]
![2021-01-24_20 15 01](https://user-images.githubusercontent.com/35677394/105628602-3650f700-5e81-11eb-933f-ee9c237a0369.png)
![2021-01-24_20 17 29](https://user-images.githubusercontent.com/35677394/105628604-37822400-5e81-11eb-9224-f6fbc7222be0.png)
![2021-01-24_20 17 26](https://user-images.githubusercontent.com/35677394/105628605-381aba80-5e81-11eb-8ed4-b1ede5d72738.png)
![2021-01-24_20 15 03](https://user-images.githubusercontent.com/35677394/105628607-381aba80-5e81-11eb-9c71-b88e0173a7f1.png)

hopper state is 'enabled' but it fails to send item into dropper, and shulker box gets disappears too.

mod list:
lithium 0.6.0 with hopperoptimization
phosphor 0.7.0 
carpet mod and carpet extra, carpet TIS additions...

**Comment by aria1th** [comment]
found issue - chunkloading

**Comment by 2No2Name** [comment]
Fixed in the latest release
