### ISSUE TITLE
Compatibility with other mods?

### ISSUE THREAD

**Issue by saransh323** [2No2Name/hopperOptimizations#24]
Is this mod compatible with mods like Lithium, Phosphor and Carpet? I use those mods on my smp server and am trying to get mods for game optimisation. please let me know if I can use these mods together and whether the “Lithium fork” will conflict with the main mod.

**Comment by QPCrummer** [comment]
I use them all together, it works just fine (:

**Comment by DragonEggBedrockBreaking** [comment]
> and whether the “Lithium fork” will conflict with the main mod.

The lithium fork is a replacement for the lithium you use. In other words, it is basically normal lithium but with one extra feature to make this mod work. Every time a new "normal" lithium release is published, 2no2name updates this mod, so don't worry about being out of date.

**Comment by saransh323** [comment]
> > and whether the “Lithium fork” will conflict with the main mod.
> 
> The lithium fork is a replacement for the lithium you use. In other words, it is basically normal lithium but with one extra feature to make this mod work. Every time a new "normal" lithium release is published, 2no2name updates this mod, so don't worry about being out of date.

Oh, thanks a lot. So I assume all I have to do is put the two mod files in my mods folder, remove Lithium, and I'll be good to go? If yes, where am I supposed to get the mod jar files? Is there a link/page for them? All I can see is the source code.

**Comment by DragonEggBedrockBreaking** [comment]
> Oh, thanks a lot. So I assume all I have to do is put the two mod files in my mods folder, remove Lithium, and I'll be good to go? If yes, where am I supposed to get the mod jar files? Is there a link/page for them? All I can see is the source code.

You can download the Lithium Fork [here](https://github.com/2No2Name/lithium-fabric/releases/). Download the second file down (the one WITHOUT `-api` at the end). You can download HopperOptimiations [here](https://github.com/2No2Name/hopperOptimizations/releases/). Download the fourth file down (WITHOUT `-dev` or `-sources` at the end).

**Comment by DragonEggBedrockBreaking** [comment]
Should this be closed?

**Comment by saransh323** [comment]
> Should this be closed?

Yes, sorry
