### ISSUE TITLE
The all too infamous, 1.17... please.

### ISSUE THREAD

**Issue by ghost** [2No2Name/hopperOptimizations#33]
I don't like saying/doing this as much as you don't like seeing this, but it would be nice to know if you have plans to update to 1.17, and if so, a possible ETA.

**Comment by DragonEggBedrockBreaking** [comment]
This mod is part of lithium in 1.17.

**Comment by 2No2Name** [comment]
I reimplemented optimizations for hoppers in lithium 0.7+ for minecraft 1.17+. https://github.com/CaffeineMC/lithium-fabric/releases
This is why this mod here is obsolete now, and will no longer be updated

**Comment by popgoesme700** [comment]
Thank you.
Did not know this, do i still need to use this for 1.16.5 if i want these optimizations?

**Comment by DragonEggBedrockBreaking** [comment]
> I reimplemented optimizations for hoppers in lithium 0.7+ for minecraft 1.17+. https://github.com/CaffeineMC/lithium-fabric/releases
> This is why this mod here is obsolete now, and will no longer be updated

So should this repo be archived?
