### ISSUE TITLE
[Bug] optimizedInventories disrupts carpet-extra's autoCraftingDropper's behavior

### ISSUE THREAD

**Issue by Neubulae** [2No2Name/hopperOptimizations#7]
When autoCraftingDropper is enabled, hoppers should only be able to pump one item in for each slot. optimizedInventories disrupts this behavior as it restores to what vanilla does: 
Expected: 
![image](https://user-images.githubusercontent.com/24774842/76855769-c8b16300-688c-11ea-8ac5-24ce1e423f79.png)
Actual behavior:
![image](https://user-images.githubusercontent.com/24774842/76855798-db2b9c80-688c-11ea-8dda-f7adfff75115.png)

**Comment by 2No2Name** [comment]
Can you try the latest 0.1.16 release? I added something that should work around this.

**Comment by samolego** [comment]
Can confirm that latest release is now working as expected. Thanks for fixing!
