### ISSUE TITLE
Duping shulker boxes in first chest slot

### ISSUE THREAD

**Issue by josephrooks** [2No2Name/hopperOptimizations#8]
Using this for the first time - just noticed that in the chest my rockets are going into, when I have optimizedInventories true, rockets that come into the chest from the sorter attached to it add +1 to the shulker box full of rockets in the chest's first slot... resulting in a stack of shulker boxes identical to the one in the first slot. The items trickling in through the hopper behind the chest are lost in the process.

Toggling optimizedInventories false fixes it and setting it to true again causes it to start happening again immediately. It only seems to affect a shulker box in the first slot of the chest - once that becomes a full stack of shulker boxes, items stop moving even if there are empty slots in the chest.

![image](https://user-images.githubusercontent.com/1420959/76944766-f374d900-68d7-11ea-8cb1-f07c3f4810cb.png)

**Comment by 2No2Name** [comment]
That is an oversight (an @ Override was missing) with huge consequences, I will prepare a new release now. Thank you for the report

**Comment by 2No2Name** [comment]
@josephrooks new release is out, from my testing the bug doesn't occur anymore

**Comment by josephrooks** [comment]
Thank you! Glad I could help, I'll install the update and let you know if anything seems off.
