### ISSUE TITLE
inventoryCheckOnBlockUpdate not documented

### ISSUE THREAD

**Issue by josephrooks** [2No2Name/hopperOptimizations#9]
Just spotted this in the list when I looked through the commands that tab complete, but there's nothing in the readme about it - what does this do exactly?

Edit: Actually found it in Releases - "cache non-existence of inventory blocks until the next block update" - but I'm not sure what this means exactly or how it differs from vanilla behavior. Is this just caching the fact that there's no container so that, for example, items in water streams aren't trying to search every block they pass over for a hopper they can enter?

**Comment by 2No2Name** [comment]
Yeah the option was supposed to be temporary until the feature is stable, as it doesn't change any relevant behavior

**Comment by 2No2Name** [comment]
Documented it in the readme now
